import type { ActivityItem, Matter, QueueItem, SavedView, SummaryMetric } from "@/lib/types";
import { dashboardMatterLinks } from "@/lib/matters-workspace/links";

export const summaryMetrics: SummaryMetric[] = [
  {
    title: "New Referrals",
    count: 8,
    description: "Need initial review and routing.",
    href: dashboardMatterLinks.newReferrals,
    trend: "3 added this week",
    tone: "neutral",
  },
  {
    title: "Missing Information",
    count: 12,
    description: "Waiting on documents or claim details.",
    href: dashboardMatterLinks.missingInformation,
    trend: "4 can move with one request",
    tone: "warning",
  },
  {
    title: "Upcoming Deadlines",
    count: 6,
    description: "Require action in the next 14 days.",
    href: dashboardMatterLinks.deadlines,
    trend: "2 due this week",
    tone: "urgent",
  },
  {
    title: "Ready for Demand",
    count: 9,
    description: "Complete enough for demand preparation.",
    href: dashboardMatterLinks.readyForDemand,
    trend: "5 over $25k",
    tone: "success",
  },
  {
    title: "Needs Follow-Up",
    count: 7,
    description: "Overdue, stale, missing, or waiting beyond follow-up.",
    href: dashboardMatterLinks.followUp,
    trend: "3 are overdue actions",
    tone: "warning",
  },
];

export const matters: Matter[] = [
  {
    id: "northstar-collins-claim",
    name: "Northstar Mutual v. Collins",
    carrier: "Northstar Mutual",
    claimNumber: "NSM-48291-26",
    assignedAdjuster: "Renee Hollis",
    carrierSupervisor: "Graham Porter",
    amountSought: 42750,
    amountRecovered: 0,
    assignedAttorney: "Eli Linden",
    assignedPerson: "Maya Patel",
    stage: "Ready for demand",
    priority: "High priority",
    nextAction: "Finalize demand package",
    nextActionDueDate: "2026-07-05",
    statuteDeadline: "2026-07-10",
    lastUpdated: "2026-07-02",
    lastSubstantiveActivity: "2026-07-02",
    daysSinceLastSubstantiveActivity: 1,
    status: "Ready for demand",
    type: "Auto subrogation",
    deadlineVerified: true,
    followUpReasons: ["overdue_next_action", "upcoming_deadline"],
    notes: "Police report, repair estimate, and payment ledger are complete.",
  },
  {
    id: "harbor-bend-storage-loss",
    name: "Harbor Bend Storage Loss",
    carrier: "Summit Casualty",
    claimNumber: "SC-77104-26",
    assignedAdjuster: "Owen Mercer",
    carrierSupervisor: "Lena Ortiz",
    amountSought: 18400,
    amountRecovered: 0,
    assignedAttorney: "Jordan Lee",
    assignedPerson: "Nora Chen",
    stage: "Missing information",
    priority: "Urgent",
    nextAction: "Request signed proof of loss",
    nextActionDueDate: "2026-07-01",
    statuteDeadline: "2026-07-08",
    lastUpdated: "2026-07-01",
    lastSubstantiveActivity: "2026-06-18",
    daysSinceLastSubstantiveActivity: 15,
    status: "Missing information",
    type: "Property recovery",
    deadlineVerified: false,
    followUpReasons: ["overdue_next_action", "unverified_statute_deadline", "upcoming_deadline"],
    notes: "Coverage position is clear, but proof package is incomplete.",
  },
  {
    id: "lakeview-delivery-collision",
    name: "Lakeview Delivery Collision",
    carrier: "Evergreen Indemnity",
    claimNumber: "EGI-19577-25",
    assignedAdjuster: "Iris Bell",
    carrierSupervisor: "Marcus Vale",
    amountSought: 76500,
    amountRecovered: 18500,
    assignedAttorney: "Eli Linden",
    assignedPerson: "Eli Linden",
    stage: "Negotiation",
    priority: "High priority",
    nextAction: "Respond to counteroffer",
    nextActionDueDate: "2026-07-06",
    statuteDeadline: "2026-07-15",
    lastUpdated: "2026-07-03",
    lastSubstantiveActivity: "2026-07-03",
    daysSinceLastSubstantiveActivity: 0,
    status: "Negotiation",
    type: "Commercial auto",
    deadlineVerified: true,
    followUpReasons: ["overdue_next_action", "upcoming_deadline"],
    notes: "Defense carrier offered partial liability based on dispatch logs.",
  },
  {
    id: "cedar-ridge-water-damage",
    name: "Cedar Ridge Water Damage",
    carrier: "Pioneer Risk",
    claimNumber: "PR-66012-26",
    assignedAdjuster: "Theo Grant",
    amountSought: 29225,
    amountRecovered: 0,
    assignedAttorney: "Amara Ross",
    assignedPerson: "Maya Patel",
    stage: "Investigation",
    priority: "Normal",
    nextAction: "Confirm maintenance vendor identity",
    nextActionDueDate: "2026-07-09",
    statuteDeadline: "2026-07-18",
    lastUpdated: "2026-06-30",
    lastSubstantiveActivity: "2026-06-02",
    daysSinceLastSubstantiveActivity: 31,
    status: "Investigation",
    type: "Property recovery",
    deadlineVerified: true,
    followUpReasons: ["stale_matter", "upcoming_deadline"],
    notes: "Tenant statement and mitigation invoices are in review.",
  },
  {
    id: "metro-fleet-rear-end",
    name: "Metro Fleet Rear-End Loss",
    carrier: "Beacon Insurance",
    claimNumber: "BCN-30618-26",
    assignedAdjuster: "Priya Nair",
    amountSought: 13100,
    amountRecovered: 0,
    assignedAttorney: "Jordan Lee",
    assignedPerson: "Nora Chen",
    stage: "New referral",
    priority: "Normal",
    nextAction: "Complete intake triage",
    nextActionDueDate: "2026-07-04",
    statuteDeadline: "2026-07-12",
    lastUpdated: "2026-07-02",
    lastSubstantiveActivity: "2026-07-02",
    daysSinceLastSubstantiveActivity: 1,
    status: "New referral",
    type: "Auto subrogation",
    deadlineVerified: false,
    followUpReasons: ["overdue_next_action", "unverified_statute_deadline", "upcoming_deadline"],
    notes: "Referral arrived with invoice bundle and contact sheet.",
  },
  {
    id: "oak-terrace-fire-deductible",
    name: "Oak Terrace Fire Deductible",
    carrier: "Crestline Assurance",
    claimNumber: "CRA-92044-25",
    assignedAdjuster: "Nadine Brooks",
    carrierSupervisor: "Victor Shaw",
    amountSought: 98500,
    amountRecovered: 61500,
    assignedAttorney: "Amara Ross",
    assignedPerson: "Amara Ross",
    stage: "Under review",
    priority: "Low priority",
    nextAction: "Review settlement authority",
    nextActionDueDate: "2026-07-21",
    statuteDeadline: "2026-08-01",
    lastUpdated: "2026-06-28",
    lastSubstantiveActivity: "2026-06-28",
    daysSinceLastSubstantiveActivity: 5,
    status: "Under review",
    type: "Property recovery",
    deadlineVerified: true,
    followUpReasons: [],
    notes: "Internal authority note is pending partner review.",
  },
  {
    id: "fairlane-contractor-overpayment",
    name: "Fairlane Contractor Overpayment",
    carrier: "Meridian Claims",
    claimNumber: "MCL-11803-26",
    assignedAdjuster: "Caleb Stone",
    amountSought: 22300,
    amountRecovered: 0,
    assignedAttorney: "Eli Linden",
    assignedPerson: "Maya Patel",
    stage: "Awaiting client",
    priority: "Normal",
    nextAction: "Confirm recovery target",
    nextActionDueDate: "2026-07-11",
    statuteDeadline: "2026-07-24",
    lastUpdated: "2026-06-29",
    lastSubstantiveActivity: "2026-06-03",
    daysSinceLastSubstantiveActivity: 30,
    awaitingResponseDueDate: "2026-06-27",
    status: "Awaiting client",
    type: "Payment recovery",
    deadlineVerified: true,
    followUpReasons: ["stale_matter", "awaiting_overdue_response"],
    notes: "Client is confirming whether vendor reconciliation is final.",
  },
  {
    id: "brookfield-glass-impact",
    name: "Brookfield Glass Impact",
    carrier: "Anchor General",
    claimNumber: "AG-55820-26",
    assignedAdjuster: "Marin Ellis",
    amountSought: 8700,
    amountRecovered: 8700,
    assignedAttorney: "Jordan Lee",
    assignedPerson: "Nora Chen",
    stage: "Closed",
    priority: "Low priority",
    nextAction: "Archive matter summary",
    nextActionDueDate: "2026-08-14",
    statuteDeadline: "2026-08-14",
    lastUpdated: "2026-06-26",
    lastSubstantiveActivity: "2026-06-26",
    daysSinceLastSubstantiveActivity: 7,
    status: "Closed",
    type: "Property recovery",
    deadlineVerified: true,
    followUpReasons: [],
    notes: "Recovery posted and closing memo is ready.",
  },
  {
    id: "rivergate-slip-loss",
    name: "Rivergate Slip Loss",
    carrier: "Summit Casualty",
    claimNumber: "SC-88420-26",
    assignedAdjuster: "Owen Mercer",
    amountSought: 51200,
    amountRecovered: 0,
    assignedAttorney: "Amara Ross",
    assignedPerson: "Nora Chen",
    stage: "No immediate action",
    priority: "Normal",
    statuteDeadline: "2026-09-02",
    lastUpdated: "2026-06-20",
    lastSubstantiveActivity: "2026-05-28",
    daysSinceLastSubstantiveActivity: 36,
    status: "No immediate action",
    type: "Premises recovery",
    deadlineVerified: true,
    followUpReasons: ["missing_next_action", "stale_matter"],
    notes: "Responsible-party information is known, but no next action has been assigned.",
  },
];

export const priorityQueue: QueueItem[] = matters
  .filter((matter) => matter.followUpReasons.length > 0 || matter.priority === "Urgent" || matter.priority === "High priority")
  .slice(0, 7);

export const recentMatters = [...matters]
  .sort((a, b) => b.lastUpdated.localeCompare(a.lastUpdated))
  .slice(0, 5);

export const activityItems: ActivityItem[] = [
  {
    id: "activity-1",
    matterId: "northstar-collins-claim",
    title: "Demand packet checked",
    description: "Repair ledger and carrier payment summary were matched.",
    date: "2026-07-02",
  },
  {
    id: "activity-2",
    matterId: "northstar-collins-claim",
    title: "Deadline confirmed",
    description: "Limitation date verified against loss date and jurisdiction.",
    date: "2026-07-01",
  },
  {
    id: "activity-3",
    matterId: "northstar-collins-claim",
    title: "Missing item cleared",
    description: "Police report uploaded by claims contact.",
    date: "2026-06-29",
  },
];

export const savedViews: SavedView[] = [
  {
    id: "view-needs-follow-up",
    name: "Needs Follow-Up",
    page: "matters",
    scope: "shared",
    description: "Overdue actions, stale matters, missing actions, and unverified statute deadlines.",
  },
  {
    id: "view-my-adjuster-files",
    name: "Renee Hollis Files",
    page: "matters",
    scope: "personal",
    description: "Matters assigned to Renee Hollis with open next actions.",
  },
  {
    id: "view-ready-demand",
    name: "Ready for Demand",
    page: "matters",
    scope: "shared",
    description: "Matters with sufficient support for demand preparation.",
  },
];

export function getMatterById(id: string): Matter {
  return matters.find((matter) => matter.id === id) ?? matters[0];
}
